version: '3.4'
services:
  r_base:
    image: fdrennan/environ:latest
    # image: fdrennan/environ:beta
    # image: fdrennan/environ:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    environment:
      R_TEST: testing
    volumes:
      - ./main.R:/home/productor/main.R
      - ./.Renviron.docker:/home/productor/.Renviron
      - ./shiny_logs:/var/log/shiny-server
      - ./app.R:/home/productor/app/app.R
      - ./files_to_print:/home/productor/app/files_to_print
    user: 'root'
    ports:
      - "80:3000"
    command: ["Rscript", "/home/productor/main.R"]

volumes:
  shiny_logs:
